cat /sys/bus/cpu/devices/cpu0/online
cat /sys/bus/cpu/devices/cpu1/online
cat /sys/bus/cpu/devices/cpu2/online
cat /sys/bus/cpu/devices/cpu3/online
cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq
cat /sys/devices/system/cpu/cpu1/cpufreq/scaling_cur_freq
cat /sys/devices/system/cpu/cpu2/cpufreq/scaling_cur_freq
cat /sys/devices/system/cpu/cpu3/cpufreq/scaling_cur_freq
cat /sys/kernel/cluster/active
cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_available_frequencies
cat /sys/devices/system/cpu/cpu1/cpufreq/scaling_available_frequencies
cat /sys/devices/system/cpu/cpu2/cpufreq/scaling_available_frequencies
cat /sys/devices/system/cpu/cpu3/cpufreq/scaling_available_frequencies
